version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cinco
      POSTGRES_DB: worker
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
